spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        default-page-size: 5
        one-indexed-parameters: true
        max-page-size: 2000

  datasource:
    url: jdbc:h2:mem:eddylog;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true

eddy:
  jwt-key: "ojUnbrkuQNSr2Xny1QmYxvIFmaALXtr8TdkXFHVXuko="

